### PR TITLE
Fix: Address issue #891->cleanup of apidelay,and Refactor addr assign…

### LINKED ISSUE #891: Error in fetching user rank in leaderboard !
Details : https://www.loom.com/share/881adfab24264b04a2d0fdc8590e2f57?sid=ca7e3e70-aa71-4e6e-818d-74feb5346b4b

### PR DESCRIPTION
**Pull request by snehaa-eth**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

Resolves: #891 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new state variable for managing leaderboard toppers, enhancing leaderboard data visibility.
	- Added functionality to fetch and display leaderboard toppers based on user address.
	- Integrated a new wallet connector ("Okx Wallet") for improved user options.
	- Added a "Copy Address" feature to the wallet button for easier address management.
	- Updated transaction execution methods across multiple components for improved performance.
  
- **Bug Fixes**
	- Improved data fetching logic for leaderboard results, ensuring accurate updates and state management.
	- Enhanced type safety in wallet connection processes.
	- Updated the error message formatting in the error screen for clarity.

- **Chores**
	- Updated the `starknetkit` dependency version for improved performance and features.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
The PR doesn't build, so I cannot test. Please make sure that it builds before pushing! You can use `npm run build`
image

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Please remove changes made to package-lock.json

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Code looks clean! Please review the suggestions done by Rabbit, especially for the `any`.
But I am still able to reproduce the bug:
image


Here is what I do to get it:
I switch between these tabs (waiting after each click that it fully loads) until the dashboard shows wrong values
Screenshot 2024-11-02 at 7 59 23 PM

I think there is an issue with useEffects and api calls

File: app/leaderboard/page.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ import Divider from "@mui/material/Divider";
 import Blur from "@components/shapes/blur";
 import RankingsTable from "@components/leaderboard/RankingsTable";
 import { TOP_50_TAB_STRING } from "@constants/common";
-import { hexToDecimal } from "@utils/feltService";
+// import {  } from "@utils/feltService";
```
Comment (Marchand-Nicolas) [inline app/leaderboard/page.tsx]: No need to have this comment

File: components/navbar/walletButton.tsx [hunk 2]
```diff
@@ -44,7 +44,9 @@ const WalletButton: FunctionComponent<WalletButtonProps> = ({
   const [unfocus, setUnfocus] = useState<boolean>(false);
   const network = currentNetwork === "TESTNET" ? "testnet" : "mainnet";
   const isWebWallet =
-    (connector as Connector)?.wallet?.id === "argentWebWallet";
+    (connector as Connector)?.id === "argentWebWallet";
+
+    // console.log(connector?.id,"wallet")
```
Comment (Marchand-Nicolas) [inline components/navbar/walletButton.tsx]: No need to keep this comment too

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Very small review and I think we're good, well done!

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm!
