### PR TITLE
fix: quest info mismatch

### LINKED ISSUE #804: Collection quest info mismatch !
https://www.loom.com/share/b53911f887c64c9c87d56932f071057f?sid=4a333fa9-5384-44e5-a560-98b8f776c0cb

### PR DESCRIPTION
**Pull request by od-hunter**
# Pull Request type

- Bugfix

Resolves: #804

## Other information
Fix quest info mismatch

## Summary by CodeRabbit

- **New Features**
	- Improved accuracy in tracking and displaying completed boosts by introducing a time-based filtering criterion.
	- Enhanced user feedback with a more precise display of completed boosts relative to the visible list.

- **Bug Fixes**
	- Resolved discrepancies in completion status display by updating the logic to reflect only the filtered list of boosts.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Thanks for your PR!
The code looks clean, but I have an E2E issue.
image

I am seeing 1/0 instead of 1/1

We can see there is actually one boost shown here:
image

I think you are getting this issue because an expired boost is not necessarily hidden. I suggest you to look for the "hidden" field inside the boost object.

**Comment by Marchand-Nicolas** [comment]
I suggest you to check that code:
image
It might contains issues (should check the "hidden" field instead of the expiry date imo)

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
The "completedBoostNumber" was correct, you can keep the original version:
```tsx
const completedBoostNumber = useMemo(
    () => boosts?.filter((b) => completedBoostIds?.includes(b.id)).length,
```

The issue is more one the total amount here:
image
You should only count in the total the quests that are either not expired or completed.

The aim is that:
 - If there are 3 expired quests and 1 not expired, and that I completed none, it should show "0/1"
 - But if among these 3 expired quests I did 1, it should show "1/2"
 
 Please write your own logic instead of the one from "displayBoosts" as this is used to display the boosts that the user can claim (this is not exactly the same)

File: components/pages/home/questAndCollectionTabs.tsx [hunk 1]
```diff
@@ -112,9 +113,24 @@ const QuestAndCollectionTabs: FunctionComponent<
...
   }, [address]);
 
+  useEffect(() => {
+    const fetchRelevantBoosts = async () => {
+      if(!completedQuestIds) return
+      const relevantBoosts = boosts.filter(
+        (b) =>
+          !((new Date().getTime() - b.expiry) / MILLISECONDS_PER_WEEK <= 3 &&
+            b.expiry < Date.now()) ||
+          b.quests.some((quest) => completedQuestIds.includes(quest))
```
Comment (Marchand-Nicolas) [inline components/pages/home/questAndCollectionTabs.tsx]: Here I would simply keep
```tsx
b.expiry > Date.now()) ||
          b.quests.some((quest) => completedQuestIds.includes(quest))
```
So that it only returns quests that aren't expired or quests that are completed

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
I think there is one last thing to change and we can merge!

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm! Thanks for your work :)

**Comment by od-hunter** [comment]
Thank you ser..I’m open to more issues.🫡
