### PR TITLE
Fix: Added hover effect on cancel animation

### LINKED ISSUE #1043: Refont quiz - All pages - "Cancel" button hover animation
## Description 📹

Current : 
Image

Figma File : 
https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6827-7696&t=mT8nTLuWNPWeMAet-1

**Currently, there is no hover animation on the "cancel" button. Add the same animation to the "cancel" button as the one on the "back" button, reducing the opacity and increasing it on hover.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by snehaa-eth**
close #1043 

## Summary by CodeRabbit

- **New Features**
  - Enhanced the button component to support additional custom styling.
  - Introduced a new option in screen layouts to control title highlighting.

- **Style**
  - Updated the quiz interface for a more consistent button appearance, including a newly styled close button.
  - Refined the layout with improved spacing, larger titles, and responsive design adjustments for the close button.
  - Adjusted styles for various components to improve overall visual presentation.

### CODE REVIEW

**Comment by snehaa-eth** [comment]
@Marchand-Nicolas please kindly review it

File: components/UI/button.tsx [hunk 1]
```diff
@@ -16,17 +17,14 @@ const Button: FunctionComponent<ButtonProps> = ({
   disabled = false,
   color = "primary",
   loading = false,
+  className = "",
```
Comment (Marchand-Nicolas) [inline components/UI/button.tsx]: Please avoid passing class names in the props. Can you find another way ?

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image
There is too much spacing between the button and the text. Can you only keep the space in green ? Not the orange one ?

**Comment by Marchand-Nicolas** [comment]
The orange part is the margin, and the green one is the padding

**Comment by snehaa-eth** [comment]
fixed the margin issue

File: styles/components/quests/quiz.module.css [hunk 2]
```diff
@@ -15,16 +15,17 @@
   overflow: hidden auto;
 }
 
-.mainContainer:has(.menu) {
+/* .mainContainer:has(.menu) {
```
Comment (Marchand-Nicolas) [inline styles/components/quests/quiz.module.css]: Please delete the code instead of commenting it

Comment (Marchand-Nicolas) [reply styles/components/quests/quiz.module.css]: If you intended to not use this class anymore

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm

**Comment by Marchand-Nicolas** [comment]
@Snehagupta1907 can you fix the conflicts please

**Comment by snehaa-eth** [comment]
fixed

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect lgtm
