### PR TITLE
Fix: Merge download buttons into reusable DownloadButton component. Close #1007

### LINKED ISSUE #1007: Merge download components
## Description 📹

**Merge `components/quests/downloadQuestUsersButton.tsx`, `components/admin/DownloadBoostWinnersButton.tsx`, and `components/admin/DownloadQuestParticipantsButton.tsx` into one single reusable component.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] Create a new reusable component `DownloadButton.tsx` in a common or shared directory (e.g., `components/shared/`).
   - [ ] Implement a prop-based structure to allow flexibility for different use cases (e.g., button label, API endpoint, query parameters).
     ```tsx
     import React from "react";

     interface DownloadButtonProps {
       label: string;
       endpoint: string;
       queryParams?: Record<string, string | number>;
     }

     const DownloadButton: React.FC<DownloadButtonProps> = ({ label, endpoint, queryParams }) => {
       const handleDownload = async () => {
         const query = queryParams
           ? "?" +
             new URLSearchParams(queryParams as Record<string, string>).toString()
           : "";
         const url = `${endpoint}${query}`;
         const response = await fetch(url);
         const blob = await response.blob();
         const link = document.createElement("a");
         link.href = URL.createObjectURL(blob);
         link.download = `${label}.csv`;
         link.click();
       };

       return <button onClick={handleDownload}>{label}</button>;
     };

     export default DownloadButton;
     ```
   - [ ] Replace `DownloadQuestUsersButton`, `DownloadBoostWinnersButton`, and `DownloadQuestParticipantsButton` with the new reusable `DownloadButton` component.
     - [ ] Update the props as needed to maintain functionality for each use case.
   - [ ] Remove the old button components (`downloadQuestUsersButton.tsx`, `DownloadBoostWinnersButton.tsx`, `DownloadQuestParticipantsButton.tsx`).

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Merge download buttons into reusable DownloadButton component"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Elite-tch**
close: #1007

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

Resolves: #NA

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `DownloadButton` component for simplified file downloads across multiple sections of the application.
	- Added download functionality for Boost Winners, Quest Participants, and Quest Users with configurable endpoints and parameters.

- **Refactor**
	- Standardized download process by replacing individual download handlers with a centralized `DownloadButton` component.
	- Simplified download logic and improved code reusability.

- **Bug Fixes**
	- Removed outdated components that previously handled downloads, ensuring a cleaner codebase and reducing potential errors.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Please check the comments made by the AI.
Also, the buttons do not render well
image

**Comment by Elite-tch** [comment]
All issues have been resolved

File: components/shared/DownloadButton.tsx [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    } catch (error) {
+      console.error("Download failed:", error);
+      showNotification('Download failed', 'error');
+    } finally {
+      setIsLoading(false);
+    }
+  };
+
+  return (
+    <button onClick={handleDownload} disabled={isLoading}>
```
Comment (Marchand-Nicolas) [inline components/shared/DownloadButton.tsx]: You should not use a <button, but rather a <Button (like the ones that were used before.
This is why it's still not looking good

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
The buttons are still not rendering good.
image
Now I even get an error when clicking them, where it was working fine before in my first review.
Please test your code

File: components/shared/DownloadButton.tsx (hunk 1 above)
Comment (Elite-tch) [reply components/shared/DownloadButton.tsx]: ok

File: components/admin/DownloadBoostWinnersButton.tsx [hunk 2]
```diff
@@ -2,6 +2,7 @@ import React from "react";
 import Button from "@components/UI/button";
 import { useNotification } from "@context/NotificationProvider";
```
Comment (Marchand-Nicolas) [inline components/admin/DownloadBoostWinnersButton.tsx]: The aim of this issue is to remove these three components, and directly use the DownloadButton you created.

File: components/admin/DownloadBoostWinnersButton.tsx [hunk 3]
```diff
@@ -28,9 +29,12 @@ const DownloadBoostWinnersButton: React.FC<DownloadBoostWinnersButtonProps> = ({
   };
 
   return (
-    <Button onClick={handleDownload}>
-      <p>Download boost winners</p>
-    </Button>
+    <DownloadButton 
+    label="Download Boost Winners" 
+    endpoint={`/api/boost-winners`} // Ensure the endpoint starts with /api/
```
Comment (Marchand-Nicolas) [inline components/admin/DownloadBoostWinnersButton.tsx]: For the endpoint, it should not be a url, but a function. You should put () => AdminService.getBoostWinnersByBoostId({ id: Number(boostId) })

File: components/shared/DownloadButton.tsx [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+    setIsLoading(true);
+    abortControllerRef.current?.abort();
+    abortControllerRef.current = new AbortController();
+    try {
+      const query = queryParams
+        ? "?" +
+          new URLSearchParams(queryParams as Record<string, string>).toString()
+        : "";
+      const url = `${endpoint}${query}`;
+      const response = await fetch(url, {
```
Comment (Marchand-Nicolas) [inline components/shared/DownloadButton.tsx]: Here you should call the endpoint function, as said on my previous comment

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Not working & not doing what was asked in the issue, but you're not that far from the end!

File: components/shared/DownloadButton.tsx (hunk 4 above)
Comment (Elite-tch) [reply components/shared/DownloadButton.tsx]: thanks i understand it better now

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
https://github.com/lfglabs-dev/starknet.quest/pull/1038#discussion_r1929797590

**Comment by Marchand-Nicolas** [comment]
Also please read the ai's comment, it will help you a lot

**Comment by Marchand-Nicolas** [comment]
You can ask questions to the ai

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Tell me if you can't do this issue, and I assign someone else.
You're not listening to my reviews and not testing your code.
I repeat again, the aim of the issue is to delete these three components:
components/admin/DownloadBoostWinnersButton.tsx
components/admin/DownloadQuestParticipantsButton.tsx
components/quests/downloadQuestUsersButton.tsx
So please delete them and use your new component instead.
Also, as I said, do not do a fetch request, endpoint() is already doing the request

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm
