### PR TITLE
Invalid boost Id fixed

### LINKED ISSUE #567: Handle invalid boost ids page
Currently when we navigate to - https://starknet.quest/quest-boost/27, you might notice that the loader skeleton doesn't go away. We are indeed stuck in a infinite loading state because there is no boost id as 27. In the same scenario if someone comes on page - https://starknet.quest/quest-boost/9 then you will see that the skeleton only exists till we fetch data and once we do ,the page is filled with relevant data.

Your task is this issue would be to handle these cases where the boost id doesnt not exist and instead of showing a infinite loading state, we will display a page which looks similar to this - https://starknet.quest/quest/29. If there is no data for a boost id then show a message like - `This boost doesn't exist !` and the button should read as - `GO BACK TO BOOSTS`. 

The expected time on this issue should be around - 0.5 business day

### PR DESCRIPTION
**Pull request by Xaxxoo**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

Resolves: #567

### CODE REVIEW

File: app/quest-boost/[boostId]/page.tsx [hunk 1]
```diff
@@ -129,55 +136,69 @@ export default function Page({ params }: BoostQuestPageProps) {
...
+                  </div>
+                ) : null}
               </div>
-            ) : null}
-          </div>
+            </>
+            )}
+            {
+              !boost && (<ErrorScreen
+                errorMessage="This quest doesn't exist !"
```
Comment (ayushtom) [inline app/quest-boost/[boostId]/page.tsx]: in the issue you might see that i give the appropriate text which go here. Can you use those as string input here?

File: app/quest-boost/[boostId]/page.tsx [hunk 2]
```diff
@@ -129,55 +136,69 @@ export default function Page({ params }: BoostQuestPageProps) {
...
+                buttonText="Go back to quests"
+                onClick={() => router.push("/")}
```
Comment (ayushtom) [inline app/quest-boost/[boostId]/page.tsx]: navigate to `/quest-boost`

**Review by ayushtom — CHANGES_REQUESTED** [review]

**Comment by Xaxxoo** [comment]
Hi @ayushtom, The text has been updated.

**Comment by ayushtom** [comment]
@Xaxxoo 
i dont see the changes. 
It still says `This quest doesn't exist`.It should have said `This boost doesn't exist !`
also this comment - https://github.com/starknet-id/starknet.quest/pull/569#discussion_r1545581108

**Comment by Xaxxoo** [comment]
@ayushtom Fixed the "quest" typo.

**Comment by ayushtom** [comment]
this ?
https://github.com/starknet-id/starknet.quest/pull/569#discussion_r1545581108

File: app/quest-boost/[boostId]/page.tsx [hunk 3]
```diff
@@ -129,55 +136,69 @@ export default function Page({ params }: BoostQuestPageProps) {
...
+                {address ? (
+                  <div>
+                    <Button
+                      disabled={buttonDisabled}
+                      onClick={handleButtonClick}
+                    >
+                      {getButtonText()}
+                    </Button>
+                  </div>
+                ) : null}
```
Comment (ayushtom) [inline app/quest-boost/[boostId]/page.tsx:191]: also i think a better solution would be to add error screen component here instead of placing a null. Two different if else covering same conditions won't make much sense

**Review by ayushtom — CHANGES_REQUESTED** [review]

File: app/quest-boost/[boostId]/page.tsx (hunk 2 above)
Comment (Xaxxoo) [reply app/quest-boost/[boostId]/page.tsx]: Navigate to /quest-boost fixed.

File: app/quest-boost/[boostId]/page.tsx (hunk 3 above)
Comment (Xaxxoo) [reply app/quest-boost/[boostId]/page.tsx:191]: This particular condition is dynamically rendering a button, so if the condition is not met nothing is rendered.

**Comment by Xaxxoo** [comment]
@ayushtom can you please make sure that you are still getting "This quest doesn't exist !" on the quest-boost page and not on the quest page.

File: app/quest-boost/[boostId]/page.tsx (hunk 3 above)
Comment (ayushtom) [reply app/quest-boost/[boostId]/page.tsx:191]: actually sorry i commented on this line. I meant line 139. 
instead of doing `boost &&  X` and `!boost && Y` you can do `boost ? return X : return Y `

**Comment by ayushtom** [comment]
> @ayushtom can you please make sure that you are still getting "This quest doesn't exist !" on the quest-boost page and not on the quest page.

yep. i think in these two commits - 
https://github.com/starknet-id/starknet.quest/pull/569/commits/3ca0178565f2c983c5270e0d1923746f874bfe0f  
https://github.com/starknet-id/starknet.quest/pull/569/commits/087672640ddc3f763922ef0593f300f32a4150d2
changes were not done at once which was described in the issue description. should have been done earlier without me pointing it out since it was a bit straightforward.
also redirect was missing which was done as the latest commit which i pointed out in my initial review [here](https://github.com/starknet-id/starknet.quest/pull/569#discussion_r1545581108) - 
https://github.com/starknet-id/starknet.quest/pull/569/commits/fbdb68c902ddce5a2da8004b54cf08c7e2af831f

i think all of these changes were in the boostId page itself from what i can see in the commits since i was reviewing that page  only

**Comment by Xaxxoo** [comment]
> > @ayushtom can you please make sure that you are still getting "This quest doesn't exist !" on the quest-boost page and not on the quest page.
> 
> yep. i think in these two commits - [3ca0178](https://github.com/starknet-id/starknet.quest/commit/3ca0178565f2c983c5270e0d1923746f874bfe0f) [0876726](https://github.com/starknet-id/starknet.quest/commit/087672640ddc3f763922ef0593f300f32a4150d2) changes were not done at once which was described in the issue description. should have been done earlier without me pointing it out since it was a bit straightforward. also redirect was missing which was done as the latest commit which i pointed out in my initial review [here](https://github.com/starknet-id/starknet.quest/pull/569#discussion_r1545581108) - [fbdb68c](https://github.com/starknet-id/starknet.quest/commit/fbdb68c902ddce5a2da8004b54cf08c7e2af831f)
> 
> i think all of these changes were in the boostId page itself from what i can see in the commits since i was reviewing that page only

Are you saying the changes were made on the questId page instead of the quest-boost page??

**Comment by ayushtom** [comment]
> > > @ayushtom can you please make sure that you are still getting "This quest doesn't exist !" on the quest-boost page and not on the quest page.
> > 
> > 
> > yep. i think in these two commits - [3ca0178](https://github.com/starknet-id/starknet.quest/commit/3ca0178565f2c983c5270e0d1923746f874bfe0f) [0876726](https://github.com/starknet-id/starknet.quest/commit/087672640ddc3f763922ef0593f300f32a4150d2) changes were not done at once which was described in the issue description. should have been done earlier without me pointing it out since it was a bit straightforward. also redirect was missing which was done as the latest commit which i pointed out in my initial review [here](https://github.com/starknet-id/starknet.quest/pull/569#discussion_r1545581108) - [fbdb68c](https://github.com/starknet-id/starknet.quest/commit/fbdb68c902ddce5a2da8004b54cf08c7e2af831f)
> > i think all of these changes were in the boostId page itself from what i can see in the commits since i was reviewing that page only
> 
> Are you saying the changes were made on the questId page instead of the quest-boost page??

No actually the complete opposite. all my feedback is on quest boost page. Please resolve the open comments so we can merge this :)

**Comment by Xaxxoo** [comment]
@ayushtom I don't quite understand. Could you please point out what is left to do so I can complete it?

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/pull/569#discussion_r1546010602
@Xaxxoo this is left

**Comment by ayushtom** [comment]
@Xaxxoo  Changes look good. One more small change will be needed. I can see the back button on the page. I believe this shouldn't be there if a user comes on this page directly and there's nothing to go back to(it goes back to the browser home page which we don't want). I would need you to remove this back button if there is no starknet quest url path to go back to.

**Comment by ayushtom** [comment]
@Xaxxoo well i didn't want you to remove it. I actually wanted you to check if it's possible to display the back button if the redirection is to our own website and dont display it if it's going back to some other website. But never mind you can add the "back button" back, the rest of the code looks good to me. I'll explore a way to see if this is possible from my end in my spare time.

**Comment by Xaxxoo** [comment]
> @Xaxxoo well i didn't want you to remove it. I actually wanted you to check if it's possible to display the back button if the redirection is to our own website and dont display it if it's going back to some other website. But never mind you can add the "back button" back, the rest of the code looks good to me. I'll explore a way to see if this is possible from my end in my spare time.

If you want the <BackButton onClick={() => router.back()} />  to not show if the user lands in to a quest-boost that does not exist (such as http://localhost:3000/quest-boost/29), I think running a check like this works:

// Check if the user landed on the page directly
  const showButton = typeof window !== "undefined" && window.history.length === 1;
  
  then render it like this: 
  
  {showButton ? null : (
        <div className={styles.backButton}>
          <BackButton onClick={() => router.back()} />
        </div>
      )};
      
      It is all there but commented now. Check if it is OK and uncomment it.

**Review by ayushtom — APPROVED** [review]
lgtm
