### PR TITLE
Fix: color background of the APR, TVL and Daily reward filters/Hover

### LINKED ISSUE #1033: Change the color background of the APR, TVL and Daily reward filters/Hover
## Description 📹

Current : 
Image

New design :
Hover
Image

Down sorting selected
Image

Up sorting selected
Image

Default state
Image

Figma File : 
https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6818-13092&t=blFSVBpXjC2xbCbP-1

**Change the color background of the APR, TVL, and Daily reward filters on hover and when clicked. Depending on the sorting (up, down, etc.), change the button icon and keep the color when it is selected. Remove the hover color when the sort is clicked for the third time to reset it to its original state.**

The purpose of this issue is to update the hover and active states for the APR, TVL, and Daily Reward filters on the Starknet Quest platform.
Issue Details
	•	Current State: The hover and active states for the APR, TVL, and Daily Reward filters are inconsistent with the new design specifications.
	•	Proposed State:
	•	Update the background color of the filters on hover and when clicked.
	•	Change the button icon depending on the sorting direction (up or down).
	•	Remove the hover color when the sort is clicked for the third time to reset it to its original state.
	•	Design: The updated design is available on Figma (link provided in the issue description).
Actions to Take
	1.	Fork and Branch Creation:
	•	Fork the repository and create a new branch using the issue number.
	2.	Implementation of Changes:
	•	Update the background color for hover and active states of the filters.
	•	Implement logic to change icons based on sorting direction (up, down).
	•	Ensure that clicking a filter three times resets it to its default state.
	3.	Testing and Validation:
	•	Verify that the hover and active states are correctly applied.
	•	Test locally to ensure no visual or functional regressions occur.
	•	Confirm that all changes align with the Figma design.
	4.	Commit and Submission:
	•	Make a commit with a clear message describing the updates to hover and active states.
	•	Submit a pull request closing the issue.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by portableDD**
# Pull Request type
FIX

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Code style update (formatting, renaming)

Resolves: close #1033 

## Other information

because of the background animation which is dancing the , that daily reward tab keep breaking when the padding is added to it, Iremoved it to make it remain the where it was,

## Summary by CodeRabbit

- **Refactor**
  - Improved column headers to dynamically display sorting indicators and highlight the active sort column.
  - Enhanced code formatting for better readability and consistency.

- **Style**
  - Updated table header visuals to clearly indicate sorting direction with appropriate arrow icons and background highlights.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
the hover effect is always displayed on the "APR" tab (it should only be displayed when hovered). Also there is not enough padding for the effect on the "Daily Rewards" tab

File: components/discover/defiTable.tsx [hunk 1]
```diff
@@ -249,10 +295,10 @@ export const columns: ColumnDef<TableInfo>[] = [
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 const DataTable: FunctionComponent<DataTableProps> = ({ data, loading }) => {
   const [sorting, setSorting] = useState<SortingState>([
-    {
-      id: "apr",
-      desc: true,
-    },
+    // {
```
Comment (Marchand-Nicolas) [inline components/discover/defiTable.tsx]: Aaah my bad!! Sorry, I didn't know the APR field was selected by default, that's why the hover effect was already present.
So you can bring this default behaviour back, now I understand why it was highlighted by default

File: components/discover/defiTable.tsx [hunk 2]
```diff
@@ -261,8 +307,10 @@ const DataTable: FunctionComponent<DataTableProps> = ({ data, loading }) => {
   const [liquidityFilter, setLiquidityFilter] = useState<string>();
   const [securityFilter, setSecurityFilter] = useState<string>();
   const [airdropFilter, setAirdropFilter] = useState<string>();
-  const [securityPlaceholder, setSecurityPlaceholder] = useState<string>("Security"); // Added for dynamic placeholder
-  const [airdropPlaceholder, setAirdropPlaceholder] = useState<string>("Airdrop"); // Added for dynamic placeholder
+  const [securityPlaceholder, setSecurityPlaceholder] =
+    useState<string>("Security"); // Added for dynamic placeholder
```
Comment (Marchand-Nicolas) [inline components/discover/defiTable.tsx]: Can you remove the comments begining by "// Added ..." ?

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Great! Just two very small changes and we're good. Good work!

**Review by Marchand-Nicolas — APPROVED** [review]
Well done lgtm!
