### PR TITLE
fix: improving quest list ux

### LINKED ISSUE #578: Improving UX for Disconnected Users on Quests Boost List
image

The UX on the quests boost list is problematic when the user is disconnected because we can see "see my reward," which is not possible because the user is disconnected. Therefore, remove this message by default and make it appear only when the user is connected and has completed this quest boost.

### PR DESCRIPTION
**Pull request by zintarh**
closes #578 

Pull Request Type
Improving UX for Disconnected Users on Quests Boost List

Please add the labels corresponding to the type of changes your PR introduces:

Bugfix
Resolves: The user experience problem with the "See my reward" text displaying when a user is disconnected and hasn't finished a quest has been resolved.

### CODE REVIEW

File: components/quest-boost/boostCard.tsx [hunk 1]
```diff
@@ -60,6 +60,12 @@ const BoostCard: FunctionComponent<BoostCardProps> = ({
     [userBoostCheckStatus]
   );
 
+
+  const isBoostCompleteWithAddress = useMemo(
```
Comment (ayushtom) [inline components/quest-boost/boostCard.tsx]: why is this check not added in the the `isClickable` fn? since you use both of them together

File: components/quest-boost/boostCard.tsx [hunk 2]
```diff
@@ -97,31 +105,46 @@ const BoostCard: FunctionComponent<BoostCardProps> = ({
...
-                </div>
+                {address && (
+                  <div className={styles.issuer}>
+                    {boost.expiry < Date.now() ? (
+                      hasUserCompletedBoost ? (
+                        !userBoostCheckStatus ? (
+                          boost.winner != null ? (
+                            <>
+                              <p className="text-white">See my rewards</p>
+                              <CheckIcon width="24" color="#6AFFAF" />
```
Comment (ayushtom) [inline components/quest-boost/boostCard.tsx]: i think there is a trophy icon here for see my rewards and also can you update the token addresses for the boost in so that the amount tag is rendered for all. I think currently only strk token renders
Screenshot 2024-04-14 at 2 02 43 AM

**Review by ayushtom — APPROVED** [review]
lgtm
