### PR TITLE
Fix: Add Lending Protocols category cards

### LINKED ISSUE #1092: Discover Starknet DeFi Ecosystem - Add Lending & Borrowing cards
## Description 📹

Current : 
https://github.com/lfglabs-dev/starknet.quest/issues/1090

New design :
Image

Figma File : 
https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6892-8599&t=na3qlmRHZtQ4SHZb-1

Here, after the 'current' issue has been developed, we want to add the cards for each category. The goal is to display the DeFi cards of the category to the user so they can visit it by clicking on them, which will open a new window with the DApp link. Here, we want you to add the cards for the 'Lending & Borrowing' category, and here are the links to use:

Nostra : https://nostra.finance/
Opus : https://app.opus.money/
Vesu : https://vesu.xyz/
zkLend : https://zklend.com/

#### **Issue Details**
- **Current State**: The "Lending Protocols" category does not have any cards displayed on the DeFi page.
- **Proposed State**: Add cards for the "Lending Protocols" category, allowing users to click on them and open a new window with the corresponding DApp link.
- **Design**: The updated design is available on Figma (link provided in the issue description).
- **Links to Use**:
  - ZK-Lend: https://zk-lend.com/
  - Kakarot: https://kakarot.org/
  - Starlight: https://starlight.xyz/

---

#### **Actions to Take**
- **Fork and Branch Creation**:
  - Fork the repository and create a new branch using the issue number.

- **Implementation of Changes**:
  - Add cards for the "Lending Protocols" category.
  - Ensure each card links to its respective DApp and opens in a new window when clicked.

- **Testing and Validation**:
  - Verify that all cards are displayed correctly and link to the appropriate DApps.
  - Test locally to ensure no visual or functional regressions occur.
  - Confirm that all changes align with the Figma design.

- **Commit and Submission**:
  - Make a commit with a clear message describing the addition of cards for the "Lending Protocols" category.
  - Submit a pull request closing the issue.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by iamifechi**
This PR adds the lending protocols category cards to the new section

# Pull Request type
- UI Update

Resolves: #1092

## Other information
These links were included in the issue details but they are invalid and also not present in the design note
ZK-Lend: https://zk-lend.com/
Kakarot: https://kakarot.org/
Starlight: https://starlight.xyz/

## Summary by CodeRabbit

- **New Features**
  - Introduced a DeFi category card component for displaying clickable cards with icons and titles.
  - Populated the "Payments" category with new DeFi projects, making them visible in the Discover DeFi section.

- **Style**
  - Updated and reordered visual styles for improved consistency and readability across the DeFi discovery page.

- **Chores**
  - Improved code organization and exports for easier component management.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
I think you can wait for this issue to get merged: https://github.com/lfglabs-dev/starknet.quest/issues/1090
because the title and tabs are missing in your PR

**Comment by iamifechi** [comment]
@Marchand-Nicolas Alright thanks Nico, I will check and update when #1090 is merged

**Comment by Marchand-Nicolas** [comment]
@iamifechi Just merged the PR :D 
You can pull the changes and implement your issue!

**Comment by iamifechi** [comment]
@Marchand-Nicolas all done now.
Can I do the other cards?

File: components/discover/index.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export * from "./defiOpportunityCard";
```
Comment (Marchand-Nicolas) [inline components/discover/index.ts]: Is this index.ts file really needed ? What is the usage ?

File: components/discover/defiCategoryCard.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import Image from "next/image";
```
Comment (Marchand-Nicolas) [inline components/discover/defiCategoryCard.tsx]: This file doesn't seem to be used, you can delete it

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Looks good! Just some code to clean!

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas all done now. Can I do the other cards?

Sorry, other contribs are already on it!

File: components/discover/index.ts (hunk 1 above)
Comment (iamifechi) [reply components/discover/index.ts]: Oh my bad, created these for the cards before the main PR was merged. Cleaned up now

File: components/discover/defiCategoryCard.tsx (hunk 2 above)
Comment (iamifechi) [reply components/discover/defiCategoryCard.tsx]: done. Thanks

**Comment by iamifechi** [comment]
Cleaned up now. Thanks @Marchand-Nicolas

**Review by Marchand-Nicolas — APPROVED** [review]
Very good job well done! It works perfectly
