### PR TITLE
Fix: Add reusable component for downloading quest participants using …

### LINKED ISSUE #979: New Download quest participants button
## Description 📹

**Add a new button labeled "Download quest participants" in the "Preview" tab when editing a quest. The button should call the API endpoint `/admin/quests/get_quest_participants?quest_id=<QuestId>` with an `Authorization` header to fetch a JSON response containing quest participants and download this data as a JSON file. To avoid making the `questDetails.tsx` file too heavy, implement this button as a separate reusable component, and define the request in `services/authService.ts` for reusability.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
- [ ] Add a new service method in `services/authService.ts` to fetch quest participants.
- [ ] Create a new component `DownloadQuestParticipantsButton.tsx` to handle the "Download quest participants" functionality.
- [ ] Import the service method in `DownloadQuestParticipantsButton.tsx`.
- [ ] Update `questDetails.tsx` to include this new component in the "Preview" tab.

### Update in `services/authService.ts`:

```tsx
const getQuestParticipantsByQuestId = async (params: { id: number }) => {
  try {
    const response = await fetch(
      `${baseurl}/admin/quests/get_quest_participants?quest_id=${params.id}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      }
    );
    if (!response.ok) {
      throw new Error("Failed to fetch quest participants");
    }
    return await response.json();
  } catch (err) {
    console.log("Error while getting quest participants by quest id", err);
    throw err;
  }
};

export { getQuestParticipantsByQuestId };
```

### Create `DownloadQuestParticipantsButton.tsx`:

```tsx
import React from "react";
import Button from "@components/UI/button";
import { useNotification } from "@context/NotificationProvider";
import { getQuestParticipantsByQuestId } from "@services/authService";

type DownloadQuestParticipantsButtonProps = {
  questId: string;
};

const DownloadQuestParticipantsButton: React.FC<DownloadQuestParticipantsButtonProps> = ({ questId }) => {
  const { showNotification } = useNotification();

  const handleDownload = async () => {
    try {
      const data = await getQuestParticipantsByQuestId({ id: Number(questId) });

      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `quest_${questId}_participants.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading quest participants:", error);
      showNotification("Failed to download quest participants.", "error");
    }
  };

  return (
    <Button onClick={handleDownload}>
      <p>Download quest participants</p>
    </Button>
  );
};

export default DownloadQuestParticipantsButton;
```

### Update in `questDetails.tsx`:

```tsx
import DownloadQuestParticipantsButton from "./DownloadQuestParticipantsButton";

// Inside the render function of AdminQuestDetails component:
<DownloadQuestParticipantsButton questId={questId} />
```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Add reusable component for downloading quest participants using authService"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by blessingbytes**
# Add Download Quest Participants Button

## Description
Implements a new "Download quest participants" button functionality as requested in issue #979. The button will be placed in the Preview tab when editing a quest, allowing admins to download participant data as a JSON file.

### New Files Added:
1. `components/admin/DownloadQuestParticipantsButton.tsx`: 
  - Created reusable button component for downloading quest participants
  - Manages file download process

### Modified Files
- `components/admin/questDetails.tsx`: Integrated download button
- `services/authService.ts`: Added new API endpoint method

1. `components/admin/questDetails.tsx`: 
  - Integrated download button
  
2. `services/authService.ts`
  - Added new `getQuestParticipants` method
  - Endpoint: `/admin/quests/get_quest_participants`
  - Added to AdminService exports

##Testing Approach
Tested a the download button with a json response from an api and it worked with the results:
- Button component renders correctly
- Loading states work as expected 
- File downloads successfully
- Proper error handling and notifications 

### Created just for the purpose of testing the download button implementation:
Screenshot 2024-12-15 at 21 39 51
Screenshot 2024-12-15 at 21 41 35

### Downloaded file which contains the json response(shows that the download button works correctly)
Screenshot 2024-12-15 at 21 39 34

Closes #979

## Summary by CodeRabbit

- **New Features**
	- Introduced a new button to download quest participants directly from the AdminQuestDetails component.
	- Added functionality to fetch and download quest participants data as a JSON file.

- **Bug Fixes**
	- Implemented error handling for the download process to improve user notifications.

- **Documentation**
	- Updated component and service exports to include the new DownloadQuestParticipantsButton and related functionality.

### CODE REVIEW

**Comment by blessingbytes** [comment]
### All tests are passing as expected:

Screenshot 2024-12-15 at 23 59 22
Screenshot 2024-12-15 at 23 59 29

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Really good job, the component is really cool!
Could you move the "Download quest users" button that was added by another contributor next to yours please ? (You might need to pull the changes to see it).
image

**Comment by blessingbytes** [comment]
Ok sure

**Comment by blessingbytes** [comment]
Hello @Marchand-Nicolas, Changes implemented. Thanks for reviewing

File: components/admin/questDetails.tsx [hunk 1]
```diff
@@ -238,12 +239,16 @@ const AdminQuestDetails: FunctionComponent<QuestDetailsProps> = ({
           </Button>
         </div>
         {isEdit && (
```
Comment (Marchand-Nicolas) [inline components/admin/questDetails.tsx:241]: Line 230, could you edit ` <div className="w-full flex justify-center gap-8">` by adding `flex-wrap` to the className please ? Because there is not enough space for the buttons

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: components/admin/questDetails.tsx (hunk 1 above)
Comment (blessingbytes) [reply components/admin/questDetails.tsx:241]: Hello @Marchand-Nicolas changes have been implemented. Thanks allot

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect lgtm!
