### PR TITLE
Fix: Add reusable component for downloading boost winners using authS…

### LINKED ISSUE #980: New Download boost winners button
## Description 📹

**Add a new button labeled "Download boost winners" in the "Preview" tab when editing a boost. The button should call the API endpoint `/admin/boosts/get_boost_winners?boost_id=<BoostId>` with an `Authorization` header to fetch a JSON response containing boost winners and download this data as a JSON file. To avoid making the `questDetails.tsx` file too heavy, implement this button as a separate reusable component, and define the request in `services/authService.ts` for reusability.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
- [ ] Add a new service method in `services/authService.ts` to fetch boost winners.
- [ ] Create a new component `DownloadBoostWinnersButton.tsx` to handle the "Download boost winners" functionality.
- [ ] Import the service method in `DownloadBoostWinnersButton.tsx`.
- [ ] Update the relevant file (e.g., `questDetails.tsx` or similar) to include this new component.

### Update in `services/authService.ts`:

```tsx
const getBoostWinnersByBoostId = async (params: { id: number }) => {
  try {
    const response = await fetch(
      `${baseurl}/admin/boosts/get_boost_winners?boost_id=${params.id}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      }
    );
    if (!response.ok) {
      throw new Error("Failed to fetch boost winners");
    }
    return await response.json();
  } catch (err) {
    console.log("Error while getting boost winners by boost id", err);
    throw err;
  }
};

export { getBoostWinnersByBoostId };
```

### Create `DownloadBoostWinnersButton.tsx`:

```tsx
import React from "react";
import Button from "@components/UI/button";
import { useNotification } from "@context/NotificationProvider";
import { getBoostWinnersByBoostId } from "@services/authService";

type DownloadBoostWinnersButtonProps = {
  boostId: string;
};

const DownloadBoostWinnersButton: React.FC<DownloadBoostWinnersButtonProps> = ({ boostId }) => {
  const { showNotification } = useNotification();

  const handleDownload = async () => {
    try {
      const data = await getBoostWinnersByBoostId({ id: Number(boostId) });

      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `boost_${boostId}_winners.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading boost winners:", error);
      showNotification("Failed to download boost winners.", "error");
    }
  };

  return (
    <Button onClick={handleDownload}>
      <p>Download boost winners</p>
    </Button>
  );
};

export default DownloadBoostWinnersButton;
```

### Update in `questDetails.tsx` or relevant file:

```tsx
import DownloadBoostWinnersButton from "./DownloadBoostWinnersButton";

// Inside the render function of the relevant component:
<DownloadBoostWinnersButton boostId={boostId} />
```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Add reusable component for downloading boost winners using authService"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by gadyrcdz**
# Add Download Boost Winners Button

## Description
Implements a new "Download boost winners" button functionality as requested in issue #980. The button will be added to the appropriate UI (e.g., `questDetails.tsx`), allowing admins to download boost winners data as a JSON file.

---

### New Files Added:
- **`components/admin/DownloadBoostWinnersButton.tsx`:**
  - Created a reusable button component for downloading boost winners.
  - Manages the file download process and integrates with the new service method.

---

### Modified Files:
- **`components/admin/questDetails.tsx`:**
  - Integrated the `DownloadBoostWinnersButton` component.
  - Positioned the button appropriately within the admin interface.

- **`services/authService.ts`:**
  - Added a new API endpoint method `getBoostWinners`.
  - **Endpoint:** `/admin/boost/get_winners`.
---

### Unit Tests:
- Verified proper integration of the button component.

### Tests Passed 
1. [x] All the test
image

Resolves: #980 

## Summary by CodeRabbit

- **New Features**
	- Introduced a button for downloading boost winners in JSON format.
	- Enhanced quest details to conditionally display the download button based on user permissions and available boosts.
	- Added loading states and improved error handling during quest creation.

- **Bug Fixes**
	- Improved error notifications for boost winner downloads and quest publishing.

- **Documentation**
	- Updated types to include a new property for managing boosts associated with quests.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
It doesn't build. You can run `npm run build`

File: components/admin/questDetails.tsx [hunk 1]
```diff
@@ -24,9 +24,12 @@ import { useNotification } from "@context/NotificationProvider";
 import Button from "@components/UI/button";
 import { useRouter } from "next/navigation";
 import DownloadQuestParticipantsButton from './DownloadQuestParticipantsButton';
+import DownloadBoostWinnersButton from "./DownloadBoostWinnersButton";
+
 
 type QuestDetailsProps = {
   quest: QuestDocument;
+  boost: ClaimableQuestDocument;
```
Comment (Marchand-Nicolas) [inline components/admin/questDetails.tsx]: Don't add this new param. The boostId is quest.boosts[0].id. Hide the button if quest.boosts.length == 0

File: constants/common.ts [hunk 2]
```diff
@@ -1,5 +1,6 @@
 export const QuestDefault = {
   id: 0,
+  boostId: 0,
```
Comment (Marchand-Nicolas) [inline constants/common.ts]: Remove this

File: services/authService.ts [hunk 3]
```diff
@@ -671,4 +692,6 @@ export const AdminService = {
   updateNftUri,
   addUser,
   getQuestParticipantsByQuestId,
+  getBoostWinnersByBoostId,
 };
+export { getBoostWinnersByBoostId };
```
Comment (Marchand-Nicolas) [inline services/authService.ts]: Do not add a second export

File: app/admin/quests/dashboard/[questId]/page.tsx [hunk 4]
```diff
@@ -820,6 +820,7 @@ export default function Page({ params }: QuestIdProps) {
       return (
         <AdminQuestDetails
           quest={questData}
+          boost={questData}
```
Comment (Marchand-Nicolas) [inline app/admin/quests/dashboard/[questId]/page.tsx]: Remove this

File: app/admin/quests/create/page.tsx [hunk 5]
```diff
@@ -494,6 +496,7 @@ export default function Page() {
       return (
         <AdminQuestDetails
           quest={finalQuestData}
+          boost={finalQuestData}
```
Comment (Marchand-Nicolas) [inline app/admin/quests/create/page.tsx]: Remove this

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Please remove package-lock.json from the PR

File: components/admin/questDetails.tsx (hunk 1 above)
Comment (Marchand-Nicolas) [reply components/admin/questDetails.tsx]: In fact I think the best would be to map quest.boosts. 
Something like that:
```tsx
quest.boosts.map((boost) => 
<ButtonComponent>Download Boost (#{boost.id}) Winners 
```

Because even though in most cases we only have one boost per quest, it's possible to have several

Comment (gadyrcdz) [reply components/admin/questDetails.tsx]: Hello Sir @Marchand-Nicolas, sorry for the misunderstood. In this part 
image
that you told me the boostId is quest.boosts[0].id but the "quest: QuestDocument;" of "QuestDetailsProps" doesn't have that param, Do I have to add the param or I'm doing something wrong? I'm very sorry for the question.

Comment (Marchand-Nicolas) [reply components/admin/questDetails.tsx]: Ah you can test, I think if you try console.log(quest), you should see a boosts param in it. If so you can update the QuestDocument type

Comment (gadyrcdz) [reply components/admin/questDetails.tsx]: I'm not sure if the new param of "boosts" in the QuestDocument type has to be something like this 
image
or like this 
image

Comment (Marchand-Nicolas) [reply components/admin/questDetails.tsx]: I think the first is better, if it contains an id field

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image

File: components/admin/questDetails.tsx [hunk 6]
```diff
@@ -56,7 +58,9 @@ const AdminQuestDetails: FunctionComponent<QuestDetailsProps> = ({
   const [customError, setCustomError] = useState<string>("");
   const { showNotification } = useNotification();
   const questId = quest?.id?.toString();
+  const boostId = quest?.boosts[0].boostId.toString();
```
Comment (Marchand-Nicolas) [inline components/admin/questDetails.tsx]: There is no boostId field. The field is .id
The correct type is Boost.

Also, as I said, please map the boosts.

File: components/admin/questDetails.tsx [hunk 7]
```diff
@@ -238,6 +242,11 @@ const AdminQuestDetails: FunctionComponent<QuestDetailsProps> = ({
             <p>Go To Quest</p>
           </Button>
         </div>
+        {isEdit && quest.boosts?.length > 0 && (
```
Comment (Marchand-Nicolas) [inline components/admin/questDetails.tsx]: Here you should do isEdit ? quest.boosts.map(boost => <div ...></div>

File: components/admin/questDetails.tsx (hunk 6 above)
Comment (Marchand-Nicolas) [reply components/admin/questDetails.tsx]: It'll fix the error message

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: types/backTypes.d.ts [hunk 8]
```diff
@@ -23,6 +23,7 @@ type QuestDocument = {
   expired: boolean;
   visible: boolean;
   banner?: Banner;
+  boosts: ClaimableQuestDocument[];
```
Comment (Marchand-Nicolas) [inline types/backTypes.d.ts]: Here the type should be Boost[]

[the remark this answers is not in the document]
Comment (Marchand-Nicolas) [reply types/backTypes.d.ts]: Please check AI comments, they often give you some clues or advices @gadyrcdz

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: components/admin/questDetails.tsx (hunk 7 above)
Comment (gadyrcdz) [reply components/admin/questDetails.tsx]: Got it, Sir, something like this?
image

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect lgtm!

**Comment by gadyrcdz** [comment]
> Perfect lgtm!

I'm very sorry for all of the misunderstanding Sir, and thanks for the opportunity, I appreciate!
